DROP DATABASE IF EXISTS DBFOODTRUCK;
CREATE DATABASE DBFOODTRUCK;

USE DBFOODTRUCK;

CREATE TABLE TIPOUSUARIO (
	IDTIPOUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDTIPOUSUARIO INT, FOREIGN KEY(IDTIPOUSUARIO) REFERENCES TIPOUSUARIO(IDTIPOUSUARIO),
    NOME VARCHAR(255),
    CPF VARCHAR(11) UNIQUE,
    EMAIL VARCHAR(255),
    TELEFONE VARCHAR(14),
    DATACADASTRO DATETIME,
    DATAEXPIRACAO DATETIME,
    LOGIN VARCHAR(255),
    SENHA VARCHAR(255)
);

CREATE TABLE TIPOPRODUTO(
	IDTIPOPRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE PRODUTO(
	IDPRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDTIPOPRODUTO INT, FOREIGN KEY(IDTIPOPRODUTO) REFERENCES TIPOPRODUTO(IDTIPOPRODUTO),
    NOME VARCHAR(255) UNIQUE,
    PRECO NUMERIC(10,2),
    DATACADASTRO DATETIME,
    DATAEXCLUSAO DATETIME
);



INSERT INTO TIPOUSUARIO (DESCRICAO) VALUES ('ADMINISTRADOR');
INSERT INTO TIPOUSUARIO (DESCRICAO) VALUES ('CLIENTE');
INSERT INTO TIPOUSUARIO (DESCRICAO) VALUES ('FUNCIONARIO');
INSERT INTO TIPOUSUARIO (DESCRICAO) VALUES ('ENTREGADOR');

INSERT INTO USUARIO (IDTIPOUSUARIO, NOME, CPF, EMAIL, TELEFONE, DATACADASTRO, DATAEXPIRACAO, LOGIN, SENHA) VALUES (1, 'Luis Alberto Weber', '01234567890', 'luis@gmail.com', '91111-6666', '2022-11-03', NULL, 'LUIS', 'ALBERTO');

INSERT INTO TIPOPRODUTO (DESCRICAO) VALUES ('COMIDA');
INSERT INTO TIPOPRODUTO (DESCRICAO) VALUES ('BEBIDA');
INSERT INTO TIPOPRODUTO (DESCRICAO) VALUES ('SOBREMESA');

INSERT INTO PRODUTO (IDTIPOPRODUTO, NOME, PRECO, DATACADASTRO, DATAEXCLUSAO) VALUES (1, 'Pizza', 50.00, '2022-11-03', NULL);


SELECT * FROM TIPOUSUARIO;
SELECT * FROM USUARIO;
SELECT * FROM TIPOPRODUTO;
SELECT * FROM PRODUTO;